#!/bin/bash

#Script To Start List Of Services  
#To Be Run Manually

echo -e "Please Chose From The Following Options To Start The Desired Services"

echo -e " 1) Apache\n 2) FTP\n 3) Samba\n 4) Mediatomb\n 5) All Of The Above"

read start

case $start in

1 ) sudo /etc/init.d/apache2 start
    ;;
2 ) sudo /etc/init.d/vsftpd start
    ;;
3 ) sudo /etc/init.d/samba start
    ;;
#4 )  sudo /etc/init.d/cronie start
 #   ;;
4 ) sudo /etc/init.d/mediatomb start 
    ;;
#5 ) deluge-web -f
#    ;;

5 ) sudo /etc/init.d/apache2 start &
    sudo /etc/init.d/vsftpd start  &
    sudo /etc/init.d/samba start  &
    sudo /etc/init.d/cronie start  &
    sudo /etc/init.d/mediatomb start  &
 #   deluge-web -f
    ;;

* ) echo -e " You entered $start which is not in the above options. 
              Please run start again and ensure correct usage"
esac

echo -e "Aria should be started manually by specifying the command aria -D"

